### ISSUE TITLE
Error prompt

### ISSUE THREAD

**Issue by HAOXIAN11** [LIL-JABA/lolchecker#2]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import checker
  File "C:\Users\Administrator\Desktop\LOLCHECK33\lolchecker-main\checker.py", line 6, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'

**Comment by LIL-JABA** [comment]
pip install discord_webhook
