### ISSUE TITLE
Error Request call its back message log

### ISSUE THREAD

**Issue by RikNaide** [LIL-JABA/lolchecker#3]
(2022-09-24 03:29:48.053727) Traceback (most recent call last):
  File "C:\Users\Rickey_N\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Rickey_N\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Rickey_N\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Rickey_N\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rickey_N\Desktop\LolCheak\checker.py", line 82, in checker
    token,ent,puuid,unverifmail=ath.auth(proxy)
  File "C:\Users\Rickey_N\Desktop\LolCheak\codeparts\auth.py", line 50, in auth
    data=response.json()
  File "C:\Users\Rickey_N\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by HAOXIAN11** [comment]
Yes, although my log content is not quite the same as yours

(2022-09-24 13:10:10.331724) Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\lollll4444\lolchecker-main\checker.py", line 82, in checker
    token,ent,puuid,unverifmail=ath.auth(proxy)
  File "C:\Users\Administrator\Desktop\lollll4444\lolchecker-main\codeparts\auth.py", line 50, in auth
    data=response.json()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LIL-JABA** [comment]
riot changed their ip so i have to rewrite it
maybe in a few days
